//////////////////////////////////////////////////////////////////////////////////////////////
// Code generated by protoc-gen-mapper. .
// DO NOT EDIT.
//////////////////////////////////////////////////////////////////////////////////////////////

package product

import (
	"testing"
)

func Test_ToMap(t *testing.T) {
	p := new(Product)
	p.Name = "Gopher"
	p.StarRating = new(Rating)
	p.StarRating.Count = 10
	m := p.ToMap()
	if m[ProductName] != "Gopher" {
		t.Error("Naes Dont Match")
	}
	if m[ProductStarRatingCount] != "10" {
		t.Error("Naes Dont Match")
	}
}
