// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package product

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ParentEnum int32

const (
	ParentEnum_STATUS_GOOD ParentEnum = 0
	ParentEnum_STATUS_BAD  ParentEnum = 1
)

var ParentEnum_name = map[int32]string{
	0: "STATUS_GOOD",
	1: "STATUS_BAD",
}

var ParentEnum_value = map[string]int32{
	"STATUS_GOOD": 0,
	"STATUS_BAD":  1,
}

func (x ParentEnum) String() string {
	return proto.EnumName(ParentEnum_name, int32(x))
}

func (ParentEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0}
}

type Product_StatusCode int32

const (
	Product_STATUS_GOOD Product_StatusCode = 0
	Product_STATUS_BAD  Product_StatusCode = 1
)

var Product_StatusCode_name = map[int32]string{
	0: "STATUS_GOOD",
	1: "STATUS_BAD",
}

var Product_StatusCode_value = map[string]int32{
	"STATUS_GOOD": 0,
	"STATUS_BAD":  1,
}

func (x Product_StatusCode) String() string {
	return proto.EnumName(Product_StatusCode_name, int32(x))
}

func (Product_StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0, 0}
}

type Product struct {
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string             `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	PriceDetails         string             `protobuf:"bytes,3,opt,name=price_details,json=priceDetails,proto3" json:"price_details,omitempty"`
	StarRating           *Rating            `protobuf:"bytes,4,opt,name=star_rating,json=starRating,proto3" json:"star_rating,omitempty"`
	Query                string             `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	PageNumber           float64            `protobuf:"fixed64,6,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	ResultPerPage        int32              `protobuf:"varint,7,opt,name=result_per_page,json=resultPerPage,proto3" json:"result_per_page,omitempty"`
	Indicator            bool               `protobuf:"varint,9,opt,name=indicator,proto3" json:"indicator,omitempty"`
	Code                 Product_StatusCode `protobuf:"varint,10,opt,name=code,proto3,enum=product.Product_StatusCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetPriceDetails() string {
	if m != nil {
		return m.PriceDetails
	}
	return ""
}

func (m *Product) GetStarRating() *Rating {
	if m != nil {
		return m.StarRating
	}
	return nil
}

func (m *Product) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *Product) GetPageNumber() float64 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *Product) GetResultPerPage() int32 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

func (m *Product) GetIndicator() bool {
	if m != nil {
		return m.Indicator
	}
	return false
}

func (m *Product) GetCode() Product_StatusCode {
	if m != nil {
		return m.Code
	}
	return Product_STATUS_GOOD
}

type Rating struct {
	Stars                string   `protobuf:"bytes,1,opt,name=stars,proto3" json:"stars,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Details              *Detail  `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rating) Reset()         { *m = Rating{} }
func (m *Rating) String() string { return proto.CompactTextString(m) }
func (*Rating) ProtoMessage()    {}
func (*Rating) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{1}
}

func (m *Rating) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rating.Unmarshal(m, b)
}
func (m *Rating) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rating.Marshal(b, m, deterministic)
}
func (m *Rating) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rating.Merge(m, src)
}
func (m *Rating) XXX_Size() int {
	return xxx_messageInfo_Rating.Size(m)
}
func (m *Rating) XXX_DiscardUnknown() {
	xxx_messageInfo_Rating.DiscardUnknown(m)
}

var xxx_messageInfo_Rating proto.InternalMessageInfo

func (m *Rating) GetStars() string {
	if m != nil {
		return m.Stars
	}
	return ""
}

func (m *Rating) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Rating) GetDetails() *Detail {
	if m != nil {
		return m.Details
	}
	return nil
}

type Detail struct {
	Something            string     `protobuf:"bytes,1,opt,name=something,proto3" json:"something,omitempty"`
	Nothing              string     `protobuf:"bytes,2,opt,name=nothing,proto3" json:"nothing,omitempty"`
	Penum                ParentEnum `protobuf:"varint,3,opt,name=penum,proto3,enum=product.ParentEnum" json:"penum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Detail) Reset()         { *m = Detail{} }
func (m *Detail) String() string { return proto.CompactTextString(m) }
func (*Detail) ProtoMessage()    {}
func (*Detail) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{2}
}

func (m *Detail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Detail.Unmarshal(m, b)
}
func (m *Detail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Detail.Marshal(b, m, deterministic)
}
func (m *Detail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Detail.Merge(m, src)
}
func (m *Detail) XXX_Size() int {
	return xxx_messageInfo_Detail.Size(m)
}
func (m *Detail) XXX_DiscardUnknown() {
	xxx_messageInfo_Detail.DiscardUnknown(m)
}

var xxx_messageInfo_Detail proto.InternalMessageInfo

func (m *Detail) GetSomething() string {
	if m != nil {
		return m.Something
	}
	return ""
}

func (m *Detail) GetNothing() string {
	if m != nil {
		return m.Nothing
	}
	return ""
}

func (m *Detail) GetPenum() ParentEnum {
	if m != nil {
		return m.Penum
	}
	return ParentEnum_STATUS_GOOD
}

func init() {
	proto.RegisterEnum("product.ParentEnum", ParentEnum_name, ParentEnum_value)
	proto.RegisterEnum("product.Product_StatusCode", Product_StatusCode_name, Product_StatusCode_value)
	proto.RegisterType((*Product)(nil), "product.Product")
	proto.RegisterType((*Rating)(nil), "product.Rating")
	proto.RegisterType((*Detail)(nil), "product.Detail")
}

func init() { proto.RegisterFile("product.proto", fileDescriptor_f0fd8b59378f44a5) }

var fileDescriptor_f0fd8b59378f44a5 = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x41, 0x8f, 0xd3, 0x30,
	0x10, 0x85, 0xf1, 0xd2, 0x34, 0x74, 0x42, 0xdb, 0xd5, 0xc0, 0xc1, 0x12, 0x48, 0x44, 0x45, 0x42,
	0x59, 0xa4, 0x2d, 0xa8, 0x1c, 0x39, 0xed, 0x52, 0xc4, 0x8d, 0xad, 0xdc, 0xe5, 0xc2, 0x25, 0xf2,
	0x26, 0xa3, 0x12, 0xd1, 0xd8, 0xc1, 0xb1, 0x0f, 0xfc, 0x6e, 0xfe, 0x00, 0xb2, 0x9d, 0x92, 0xde,
	0xb8, 0xcd, 0xfb, 0x66, 0x34, 0x9e, 0xf7, 0x12, 0x98, 0x77, 0x46, 0xd7, 0xae, 0xb2, 0xeb, 0xce,
	0x68, 0xab, 0x31, 0x1d, 0xe4, 0xea, 0xcf, 0x05, 0xa4, 0xbb, 0x58, 0x23, 0xc2, 0x44, 0xc9, 0x96,
	0x38, 0xcb, 0x59, 0x31, 0x13, 0xa1, 0xc6, 0x1c, 0xb2, 0x9a, 0xfa, 0xca, 0x34, 0x9d, 0x6d, 0xb4,
	0xe2, 0x17, 0xa1, 0x75, 0x8e, 0xf0, 0xb5, 0xdf, 0xdd, 0x54, 0x54, 0xd6, 0x64, 0x65, 0x73, 0xec,
	0xf9, 0xe3, 0x30, 0xf3, 0x34, 0xc0, 0x6d, 0x64, 0xf8, 0x1e, 0xb2, 0xde, 0x4a, 0x53, 0x1a, 0x69,
	0x1b, 0x75, 0xe0, 0x93, 0x9c, 0x15, 0xd9, 0x66, 0xb9, 0x3e, 0x1d, 0x25, 0x02, 0x16, 0xe0, 0x67,
	0x62, 0x8d, 0xcf, 0x21, 0xf9, 0xe5, 0xc8, 0xfc, 0xe6, 0x49, 0x58, 0x17, 0x05, 0xbe, 0x82, 0xac,
	0x93, 0x07, 0x2a, 0x95, 0x6b, 0x1f, 0xc8, 0xf0, 0x69, 0xce, 0x0a, 0x26, 0xc0, 0xa3, 0xaf, 0x81,
	0xe0, 0x1b, 0x58, 0x1a, 0xea, 0xdd, 0xd1, 0x96, 0x1d, 0x99, 0xd2, 0x37, 0x78, 0x9a, 0xb3, 0x22,
	0x11, 0xf3, 0x88, 0x77, 0x64, 0x76, 0xf2, 0x40, 0xf8, 0x12, 0x66, 0x8d, 0xaa, 0x9b, 0x4a, 0x5a,
	0x6d, 0xf8, 0x2c, 0x67, 0xc5, 0x13, 0x31, 0x02, 0x7c, 0x07, 0x93, 0x4a, 0xd7, 0xc4, 0x21, 0x67,
	0xc5, 0x62, 0xf3, 0xe2, 0xdf, 0x9d, 0x43, 0x52, 0xeb, 0xbd, 0x95, 0xd6, 0xf5, 0x9f, 0x74, 0x4d,
	0x22, 0x0c, 0xae, 0xae, 0x01, 0x46, 0x86, 0x4b, 0xc8, 0xf6, 0xf7, 0x37, 0xf7, 0xdf, 0xf6, 0xe5,
	0x97, 0xbb, 0xbb, 0xed, 0xe5, 0x23, 0x5c, 0x00, 0x0c, 0xe0, 0xf6, 0x66, 0x7b, 0xc9, 0x56, 0x25,
	0x4c, 0x47, 0x9b, 0xde, 0x74, 0x3f, 0x84, 0x1e, 0x85, 0xa7, 0x95, 0x76, 0xca, 0x86, 0xbc, 0x13,
	0x11, 0x05, 0x5e, 0x41, 0x7a, 0x9e, 0xf1, 0x79, 0x80, 0x31, 0x67, 0x71, 0xea, 0xaf, 0x7e, 0xc2,
	0x34, 0x22, 0x6f, 0xb4, 0xd7, 0x2d, 0xd9, 0x1f, 0x3e, 0xf7, 0xf8, 0xc8, 0x08, 0x90, 0x43, 0xaa,
	0x74, 0xec, 0xc5, 0x4f, 0x7b, 0x92, 0x78, 0x05, 0x49, 0x47, 0xca, 0xb5, 0xe1, 0xa9, 0xc5, 0xe6,
	0xd9, 0x98, 0x81, 0x34, 0xa4, 0xec, 0x67, 0xe5, 0x5a, 0x11, 0x27, 0xde, 0x5e, 0x03, 0x8c, 0xf0,
	0xbf, 0xe6, 0x6f, 0x97, 0xdf, 0xe7, 0xe1, 0x27, 0xfc, 0x38, 0x6c, 0x7c, 0x98, 0x06, 0xf9, 0xe1,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6c, 0xca, 0xd9, 0x91, 0xa4, 0x02, 0x00, 0x00,
}
