// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package product

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	PriceDetails         string   `protobuf:"bytes,3,opt,name=price_details,json=priceDetails,proto3" json:"price_details,omitempty"`
	StarRating           *Rating  `protobuf:"bytes,4,opt,name=star_rating,json=starRating,proto3" json:"star_rating,omitempty"`
	Query                string   `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	PageNumber           float64  `protobuf:"fixed64,6,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	ResultPerPage        int32    `protobuf:"varint,7,opt,name=result_per_page,json=resultPerPage,proto3" json:"result_per_page,omitempty"`
	Indicator            bool     `protobuf:"varint,9,opt,name=indicator,proto3" json:"indicator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetPriceDetails() string {
	if m != nil {
		return m.PriceDetails
	}
	return ""
}

func (m *Product) GetStarRating() *Rating {
	if m != nil {
		return m.StarRating
	}
	return nil
}

func (m *Product) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *Product) GetPageNumber() float64 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *Product) GetResultPerPage() int32 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

func (m *Product) GetIndicator() bool {
	if m != nil {
		return m.Indicator
	}
	return false
}

type Rating struct {
	Stars                string   `protobuf:"bytes,1,opt,name=stars,proto3" json:"stars,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Details              *Detail  `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rating) Reset()         { *m = Rating{} }
func (m *Rating) String() string { return proto.CompactTextString(m) }
func (*Rating) ProtoMessage()    {}
func (*Rating) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{1}
}

func (m *Rating) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rating.Unmarshal(m, b)
}
func (m *Rating) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rating.Marshal(b, m, deterministic)
}
func (m *Rating) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rating.Merge(m, src)
}
func (m *Rating) XXX_Size() int {
	return xxx_messageInfo_Rating.Size(m)
}
func (m *Rating) XXX_DiscardUnknown() {
	xxx_messageInfo_Rating.DiscardUnknown(m)
}

var xxx_messageInfo_Rating proto.InternalMessageInfo

func (m *Rating) GetStars() string {
	if m != nil {
		return m.Stars
	}
	return ""
}

func (m *Rating) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Rating) GetDetails() *Detail {
	if m != nil {
		return m.Details
	}
	return nil
}

type Detail struct {
	Something            string   `protobuf:"bytes,1,opt,name=something,proto3" json:"something,omitempty"`
	Nothing              string   `protobuf:"bytes,2,opt,name=nothing,proto3" json:"nothing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Detail) Reset()         { *m = Detail{} }
func (m *Detail) String() string { return proto.CompactTextString(m) }
func (*Detail) ProtoMessage()    {}
func (*Detail) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{2}
}

func (m *Detail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Detail.Unmarshal(m, b)
}
func (m *Detail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Detail.Marshal(b, m, deterministic)
}
func (m *Detail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Detail.Merge(m, src)
}
func (m *Detail) XXX_Size() int {
	return xxx_messageInfo_Detail.Size(m)
}
func (m *Detail) XXX_DiscardUnknown() {
	xxx_messageInfo_Detail.DiscardUnknown(m)
}

var xxx_messageInfo_Detail proto.InternalMessageInfo

func (m *Detail) GetSomething() string {
	if m != nil {
		return m.Something
	}
	return ""
}

func (m *Detail) GetNothing() string {
	if m != nil {
		return m.Nothing
	}
	return ""
}

func init() {
	proto.RegisterType((*Product)(nil), "product.Product")
	proto.RegisterType((*Rating)(nil), "product.Rating")
	proto.RegisterType((*Detail)(nil), "product.Detail")
}

func init() { proto.RegisterFile("product.proto", fileDescriptor_f0fd8b59378f44a5) }

var fileDescriptor_f0fd8b59378f44a5 = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x31, 0x6b, 0xfb, 0x30,
	0x10, 0xc5, 0x51, 0xfe, 0xb1, 0xfd, 0xcf, 0xb9, 0x21, 0x70, 0x74, 0xd0, 0x50, 0xa8, 0x49, 0xa1,
	0xb8, 0x4b, 0x28, 0xed, 0xd8, 0xa5, 0x94, 0xce, 0x25, 0x68, 0xec, 0x62, 0x14, 0xfb, 0x48, 0x05,
	0x89, 0xe4, 0xca, 0xf2, 0xd0, 0xcf, 0xd1, 0x2f, 0x5c, 0xa4, 0x4b, 0x88, 0xb7, 0x7b, 0xbf, 0x27,
	0xee, 0x9e, 0x9f, 0x61, 0xd9, 0x7b, 0xd7, 0x8d, 0x6d, 0xd8, 0xf4, 0xde, 0x05, 0x87, 0xc5, 0x49,
	0xae, 0x7f, 0x67, 0x50, 0x6c, 0x79, 0x46, 0x84, 0xb9, 0xd5, 0x47, 0x92, 0xa2, 0x12, 0xf5, 0x42,
	0xa5, 0x19, 0x2b, 0x28, 0x3b, 0x1a, 0x5a, 0x6f, 0xfa, 0x60, 0x9c, 0x95, 0xb3, 0x64, 0x4d, 0x11,
	0xde, 0xc5, 0xdd, 0xa6, 0xa5, 0xa6, 0xa3, 0xa0, 0xcd, 0x61, 0x90, 0xff, 0xd2, 0x9b, 0xab, 0x04,
	0xdf, 0x99, 0xe1, 0x23, 0x94, 0x43, 0xd0, 0xbe, 0xf1, 0x3a, 0x18, 0xbb, 0x97, 0xf3, 0x4a, 0xd4,
	0xe5, 0xd3, 0x6a, 0x73, 0x0e, 0xa5, 0x12, 0x56, 0x10, 0xdf, 0xf0, 0x8c, 0xd7, 0x90, 0x7d, 0x8f,
	0xe4, 0x7f, 0x64, 0x96, 0xd6, 0xb1, 0xc0, 0x5b, 0x28, 0x7b, 0xbd, 0xa7, 0xc6, 0x8e, 0xc7, 0x1d,
	0x79, 0x99, 0x57, 0xa2, 0x16, 0x0a, 0x22, 0xfa, 0x48, 0x04, 0xef, 0x61, 0xe5, 0x69, 0x18, 0x0f,
	0xa1, 0xe9, 0xc9, 0x37, 0xd1, 0x90, 0x45, 0x25, 0xea, 0x4c, 0x2d, 0x19, 0x6f, 0xc9, 0x6f, 0xf5,
	0x9e, 0xf0, 0x06, 0x16, 0xc6, 0x76, 0xa6, 0xd5, 0xc1, 0x79, 0xb9, 0xa8, 0x44, 0xfd, 0x5f, 0x5d,
	0xc0, 0xba, 0x81, 0xfc, 0x12, 0x23, 0x86, 0x1a, 0x4e, 0xa5, 0xb0, 0x88, 0xb4, 0x75, 0xa3, 0x0d,
	0xa9, 0x8f, 0x4c, 0xb1, 0xc0, 0x07, 0x28, 0xa6, 0x1d, 0x4c, 0x3f, 0x90, 0x7b, 0x50, 0x67, 0x7f,
	0xfd, 0x0a, 0x39, 0xa3, 0x18, 0x64, 0x70, 0x47, 0x0a, 0x5f, 0xb1, 0x17, 0x3e, 0x72, 0x01, 0x28,
	0xa1, 0xb0, 0x8e, 0x3d, 0xae, 0xfe, 0x2c, 0xdf, 0x56, 0x9f, 0xcb, 0xf4, 0x2b, 0x5f, 0x4e, 0x27,
	0x76, 0x79, 0x92, 0xcf, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x0b, 0x34, 0xe8, 0xea, 0x01,
	0x00, 0x00,
}
